version: '3.8'

services:
  # --- User-Specific Development Environment ---
  # Each user gets an isolated instance of this service.
  # It should be run on-demand (scale-to-zero) in a production environment.
  code-server:
    image: codercom/code-server:latest
    container_name: windwalker-ide
    ports:
      - "8080:8080" # Mapped for local development access
    volumes:
      # Mounts the user's project workspace
      - ./workspace:/home/coder/workspace
      # Persists VS Code extensions and user settings
      - ./extensions:/home/coder/.local/share/code-server/extensions
      - ./vscode-config:/home/coder/.local/share/code-server/User
      # Allows using Docker from within the IDE container
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PASSWORD=windwalker2024
      - DOCKER_USER=coder
    user: "1000:1000"
    restart: unless-stopped
    command: >
      --bind-addr 0.0.0.0:8080
      --user-data-dir /home/coder/.local/share/code-server
      --extensions-dir /home/coder/.local/share/code-server/extensions
      --disable-telemetry
      /home/coder/workspace

  # --- Shared Backend Services (Phase 2 & 3) ---
  # These services will be shared across all users and should be always-on or auto-scaling.

  # Web server for the live preview iframe (Used in Phase 2)
  # In production, this might be handled by a more robust service.
  preview-server:
    image: nginx:alpine
    container_name: windwalker-preview  
    ports:
      - "3000:80"
    volumes:
      # This volume should point to the build output of the user's project
      - ./workspace/dist:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      - code-server

  # RAG API Server (To be activated in Phase 3)
  # Handles code indexing, searching, and LLM interaction.
  # api-server:
  #   build: ./api-server
  #   container_name: windwalker-api
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=development
  #   restart: unless-stopped
  #   depends_on:
  #     - meilisearch

  # Search Engine for RAG (To be activated in Phase 3)
  # meilisearch:
  #   image: getmeili/meilisearch:v1.5
  #   container_name: windwalker-search
  #   ports:
  #     - "7700:7700"
  #   environment:
  #     - MEILI_ENV=development
  #     - MEILI_MASTER_KEY=your-secure-master-key # Change this!
  #   volumes:
  #     - meili_data:/meili_data
  #   restart: unless-stopped

volumes:
  workspace_data:
  extensions_data:
  # meili_data: # Data volume for Meilisearch
